src/VitalNutri/Models/Alimento.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VitalNutri.Models
{
    public class Alimento
    {
        [Key]
        public int AlimentoId { get; set; }
        [Required]
        public string Nome { get; set; }
        [Required]
        public int? Calorias { get; set; }
        [Required]
        public int? Carboidratos { get; set; }
        [Required]
        public int? Gorduras { get; set; }
        [Required]
        public int? Proteinas { get; set; }
        [ForeignKey("NutricionistaId")]
        public int NutricionistaId { get; set; }
        public virtual Nutricionista? Nutricionista { get; set; }
        public ICollection<RefeicaoAlimento>? RefeicoesAlimentos { get; set; }
    }
}

src/VitalNutri/Areas/Nutricionista/Controllers/AlimentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VitalNutri.Data;
using VitalNutri.Models;
using VitalNutri.Services;

namespace VitalNutri.Areas.Nutricionista.Controllers
{
    [Area("Nutricionista")]
    [Authorize(Roles = "Nutricionista")]
    public class AlimentoController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly AlimentoService _alimentoService;

        public AlimentoController(ApplicationDbContext context, AlimentoService alimentoService)
        {
            _context = context;
            _alimentoService = alimentoService;
        }

        // GET: Nutricionista/Alimento
        public async Task<IActionResult> Index()
        {
            var alimentosDoUsuario = _alimentoService.ObterAlimentosDoUsuarioAtual();
            return View(alimentosDoUsuario.ToList());
            //var applicationDbContext = _context.Alimentos.Include(a => a.Nutricionista);
            //return View(await applicationDbContext.ToListAsync());
        }

        // GET: Nutricionista/Alimento/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alimento = await _context.Alimentos
                .Include(a => a.Nutricionista)
                .FirstOrDefaultAsync(m => m.AlimentoId == id);
            if (alimento == null)
            {
                return NotFound();
            }

            return View(alimento);
        }

        // GET: Nutricionista/Alimento/Create
        public IActionResult Create()
        {
            ViewData["NutricionistaId"] = new SelectList(_context.Nutricionistas, "NutricionistaId", "NutricionistaId");
            return View();
        }

        // POST: Nutricionista/Alimento/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AlimentoId,Nome,Calorias,Carboidratos,Gorduras,Proteinas,NutricionistaId")] Alimento alimento)
        {
            if (ModelState.IsValid)
            {
                _context.Add(alimento);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["NutricionistaId"] = new SelectList(_context.Nutricionistas, "NutricionistaId", "NutricionistaId", alimento.NutricionistaId);
            return View(alimento);
        }

        // GET: Nutricionista/Alimento/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alimento = await _context.Alimentos.FindAsync(id);
            if (alimento == null)
            {
                return NotFound();
            }
            ViewData["NutricionistaId"] = new SelectList(_context.Nutricionistas, "NutricionistaId", "NutricionistaId", alimento.NutricionistaId);
            return View(alimento);
        }

        // POST: Nutricionista/Alimento/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AlimentoId,Nome,Calorias,Carboidratos,Gorduras,Proteinas,NutricionistaId")] Alimento alimento)
        {
            if (id != alimento.AlimentoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(alimento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlimentoExists(alimento.AlimentoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["NutricionistaId"] = new SelectList(_context.Nutricionistas, "NutricionistaId", "NutricionistaId", alimento.NutricionistaId);
            return View(alimento);
        }

        // GET: Nutricionista/Alimento/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alimento = await _context.Alimentos
                .Include(a => a.Nutricionista)
                .FirstOrDefaultAsync(m => m.AlimentoId == id);
            if (alimento == null)
            {
                return NotFound();
            }

            return View(alimento);
        }

        // POST: Nutricionista/Alimento/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var alimento = await _context.Alimentos.FindAsync(id);
            if (alimento != null)
            {
                _context.Alimentos.Remove(alimento);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AlimentoExists(int id)
        {
            return _context.Alimentos.Any(e => e.AlimentoId == id);
        }
    }
}

src/VitalNutri/Areas/Nutricionista/Views/Alimento/Create.cshtml
@model VitalNutri.Models.Alimento

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Alimento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Calorias" class="control-label"></label>
                <input asp-for="Calorias" class="form-control" />
                <span asp-validation-for="Calorias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Carboidratos" class="control-label"></label>
                <input asp-for="Carboidratos" class="form-control" />
                <span asp-validation-for="Carboidratos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gorduras" class="control-label"></label>
                <input asp-for="Gorduras" class="form-control" />
                <span asp-validation-for="Gorduras" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Proteinas" class="control-label"></label>
                <input asp-for="Proteinas" class="form-control" />
                <span asp-validation-for="Proteinas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NutricionistaId" class="control-label"></label>
                <select asp-for="NutricionistaId" class ="form-control" asp-items="ViewBag.NutricionistaId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/VitalNutri/Areas/Nutricionista/Views/Alimento/Delete.cshtml
@model VitalNutri.Models.Alimento

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Alimento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Calorias)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Calorias)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Carboidratos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Carboidratos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gorduras)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gorduras)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Proteinas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Proteinas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nutricionista)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nutricionista.NutricionistaId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AlimentoId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/VitalNutri/Areas/Nutricionista/Views/Alimento/Details.cshtml
@model VitalNutri.Models.Alimento

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Alimento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Calorias)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Calorias)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Carboidratos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Carboidratos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gorduras)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gorduras)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Proteinas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Proteinas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nutricionista)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nutricionista.NutricionistaId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.AlimentoId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/VitalNutri/Areas/Nutricionista/Views/Alimento/Edit.cshtml
@model VitalNutri.Models.Alimento

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Alimento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AlimentoId" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Calorias" class="control-label"></label>
                <input asp-for="Calorias" class="form-control" />
                <span asp-validation-for="Calorias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Carboidratos" class="control-label"></label>
                <input asp-for="Carboidratos" class="form-control" />
                <span asp-validation-for="Carboidratos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gorduras" class="control-label"></label>
                <input asp-for="Gorduras" class="form-control" />
                <span asp-validation-for="Gorduras" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Proteinas" class="control-label"></label>
                <input asp-for="Proteinas" class="form-control" />
                <span asp-validation-for="Proteinas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NutricionistaId" class="control-label"></label>
                <select asp-for="NutricionistaId" class="form-control" asp-items="ViewBag.NutricionistaId"></select>
                <span asp-validation-for="NutricionistaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/VitalNutri/Areas/Nutricionista/Views/Alimento/Index.cshtml
@model IEnumerable<VitalNutri.Models.Alimento>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml";
}

<p>
    <a asp-area="Nutricionista" asp-controller="Alimento" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Calorias)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Carboidratos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gorduras)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Proteinas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nutricionista)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Calorias)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Carboidratos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gorduras)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Proteinas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nutricionista.NutricionistaId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.AlimentoId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.AlimentoId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.AlimentoId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>