src/VitalNutri/Models/Exercicio.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VitalNutri.Models
{
    public class Exercicio
    {
        [Key]
        public int ExercicioId { get; set; }
        [Required]
        public string Nome { get; set; }
        [Required]
        public string? Descricao { get; set; }
        [ForeignKey("TreinadorPessoalId")]
        public int TreinadorPessoalId { get; set; }
        public byte[]? Imagem { get; set; }
        public virtual TreinadorPessoal? TreinadorPessoal { get; set; }
        public ICollection<TreinoExercicio>? TreinosExercicios { get; set; }
    }
}

src/VitalNutri/Areas/TreinadorPessoal/Controllers/ExercicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VitalNutri.Data;
using VitalNutri.Models;
using VitalNutri.Services;

namespace VitalNutri.Areas.TreinadorPessoal.Controllers
{
    [Area("TreinadorPessoal")]
    [Authorize(Roles = "TreinadorPessoal")]
    public class ExercicioController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ExercicioService _exercicioService;

        public ExercicioController(ApplicationDbContext context, ExercicioService alimentoService)
        {
            _context = context;
            _exercicioService = alimentoService; // Atribua o serviço à variável local
        }

        // GET: TreinadorPessoal/Exercicio
        public async Task<IActionResult> Index()
        {
            var exerciciosDoUsuario = _exercicioService.ObterExerciciosDoUsuarioAtual();
            return View(exerciciosDoUsuario.ToList());
        }

        // GET: TreinadorPessoal/Exercicio/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exercicio = await _context.Exercicios
                .Include(e => e.TreinadorPessoal)
                .FirstOrDefaultAsync(m => m.ExercicioId == id);
            if (exercicio == null)
            {
                return NotFound();
            }

            return View(exercicio);
        }

        // GET: TreinadorPessoal/Exercicio/Create
        public IActionResult Create()
        {
            ViewData["TreinadorPessoalId"] = new SelectList(_context.TreinadoresPessoais, "TreinadorPessoalId", "TreinadorPessoalId");
            return View();
        }

        // POST: TreinadorPessoal/Exercicio/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ExercicioId,Nome,Descricao,TreinadorPessoalId,Imagem")] Exercicio exercicio)
        {
            if (ModelState.IsValid)
            {
                _context.Add(exercicio);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TreinadorPessoalId"] = new SelectList(_context.TreinadoresPessoais, "TreinadorPessoalId", "TreinadorPessoalId", exercicio.TreinadorPessoalId);
            return View(exercicio);
        }

        // GET: TreinadorPessoal/Exercicio/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exercicio = await _context.Exercicios.FindAsync(id);
            if (exercicio == null)
            {
                return NotFound();
            }
            ViewData["TreinadorPessoalId"] = new SelectList(_context.TreinadoresPessoais, "TreinadorPessoalId", "TreinadorPessoalId", exercicio.TreinadorPessoalId);
            return View(exercicio);
        }

        // POST: TreinadorPessoal/Exercicio/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ExercicioId,Nome,Descricao,TreinadorPessoalId,Imagem")] Exercicio exercicio)
        {
            if (id != exercicio.ExercicioId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(exercicio);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExercicioExists(exercicio.ExercicioId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TreinadorPessoalId"] = new SelectList(_context.TreinadoresPessoais, "TreinadorPessoalId", "TreinadorPessoalId", exercicio.TreinadorPessoalId);
            return View(exercicio);
        }

        // GET: TreinadorPessoal/Exercicio/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exercicio = await _context.Exercicios
                .Include(e => e.TreinadorPessoal)
                .FirstOrDefaultAsync(m => m.ExercicioId == id);
            if (exercicio == null)
            {
                return NotFound();
            }

            return View(exercicio);
        }

        // POST: TreinadorPessoal/Exercicio/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var exercicio = await _context.Exercicios.FindAsync(id);
            if (exercicio != null)
            {
                _context.Exercicios.Remove(exercicio);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExercicioExists(int id)
        {
            return _context.Exercicios.Any(e => e.ExercicioId == id);
        }
    }
}

src/VitalNutri/Areas/TreinadorPessoal/Views/Exercicio/Create.cshtml
@model VitalNutri.Models.Exercicio

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Exercicio</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TreinadorPessoalId" class="control-label"></label>
                <select asp-for="TreinadorPessoalId" class ="form-control" asp-items="ViewBag.TreinadorPessoalId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Imagem" class="control-label"></label>
                <input asp-for="Imagem" class="form-control" />
                <span asp-validation-for="Imagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/VitalNutri/Areas/TreinadorPessoal/Views/Exercicio/Delete.cshtml
@model VitalNutri.Models.Exercicio

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Exercicio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TreinadorPessoal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TreinadorPessoal.TreinadorPessoalId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ExercicioId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/VitalNutri/Areas/TreinadorPessoal/Views/Exercicio/Details.cshtml
@model VitalNutri.Models.Exercicio

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Exercicio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TreinadorPessoal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TreinadorPessoal.TreinadorPessoalId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ExercicioId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/VitalNutri/Areas/TreinadorPessoal/Views/Exercicio/Edit.cshtml
@model VitalNutri.Models.Exercicio

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Exercicio</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ExercicioId" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TreinadorPessoalId" class="control-label"></label>
                <select asp-for="TreinadorPessoalId" class="form-control" asp-items="ViewBag.TreinadorPessoalId"></select>
                <span asp-validation-for="TreinadorPessoalId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagem" class="control-label"></label>
                <input asp-for="Imagem" class="form-control" />
                <span asp-validation-for="Imagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/VitalNutri/Areas/TreinadorPessoal/Views/Exercicio/Index.cshtml
@model IEnumerable<VitalNutri.Models.Exercicio>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-area="TreinadorPessoal" asp-controller="Exercicio" asp-action="Create">Novo exercício</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TreinadorPessoal)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Imagem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TreinadorPessoal.TreinadorPessoalId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ExercicioId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ExercicioId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ExercicioId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>